import { createClient } from './db-gen';
import { sdk, apiUrl, clientId } from './sdk';
import { MUSE_DB_NAME } from './schema';

// Typed genql client for the muse database's generated data plane. Generated by
// the SDK's nw-dataplane-codegen bin (see src/lib/db-gen). Auth is injected per
// request from the SDK, with a 401 → refresh retry.
const url = `${apiUrl}/graphql/db/${clientId}/${MUSE_DB_NAME}`;

export const db = createClient({
	url,
	fetch: (async (input: RequestInfo | URL, init?: RequestInit) => {
		const token = await sdk.auth.getAccessToken();
		const headers = new Headers(init?.headers as HeadersInit);
		if (token) headers.set('Authorization', `Bearer ${token}`);

		let res = await fetch(input, { ...init, headers });
		if (res.status === 401) {
			const refreshed = await sdk.auth.forceRefresh();
			if (refreshed) {
				headers.set('Authorization', `Bearer ${refreshed}`);
				res = await fetch(input, { ...init, headers });
			}
		}
		return res;
	}) as typeof fetch
});
